version: "3.8"
services:
  web:
    build: ./api
    ports:
      - "8080:8080"
    container_name: air-plan-app
    restart: unless-stopped
    environment:
        APPLICATION_CONFIG_PATH: /run/secrets/app-config
    secrets:
      - app-config
secrets:
  app-config:
    file: ./app.config