openapi: 3.0.0
info:
  title: Mission Planning Discord Interaction API
  description: This API describes the interface between Discord and the Mission Planning Application
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: The base URL for the application
paths:
  /:
    get:
      summary: Returns the default response from the API.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              "Hello, world"
  /health:
    get:
      summary: Used to check the API is responsive.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              "OK"
  /interactions:
    post:
      summary: Discord interactions are sent here.
      description: This is the route for all Discord interactions. The specific interaction requested is determined by the json payload.
      responses:
        '200':    # good
          description: The default response.
          content:
            raw/json:
              "OK"
        '401':    # bad request
          description: The request was probably not signed properly